### PR TITLE
Verify using getKey callback (fixed robozevel's PR)

### PR DESCRIPTION
**Pull request by Aulos**
This is fork of robozevel's repo with updated packages, so the tests should pass

### CODE REVIEW

**Comment by kandros** [comment]
Hello @Aulos, Could you please update the readme specifying that now a promise is returned and await is required in the examples?

Thanks

**Comment by Aulos** [comment]
Hi @kandros. I've added a little bit more than you requested. Hope you like it.

**Comment by offero** [comment]
@kandros Any chance you can merge this in? I'm looking to use jwks and not secret.

**Comment by BjoernRave** [comment]
@Aulos would also like to see this merged :)

**Pull request closed without merging**
