### PR TITLE
Support whitelist for url paths

### PR DESCRIPTION
**Pull request by c3riz88**
For example : route login no need an Authorization bearer

### CODE REVIEW

**Comment by kandros** [comment]
Hi @mickaelvalmier thanks for this PR!

Can't you can just not use jwt-auth wrapper in the micro handler that maps to the login route?

If not can  you please provide an example of your use case? 

Thanks

**Comment by c3riz88** [comment]
Hi,

In fact, i have a single entry point for all requests provided and a lot of middlewares like that :
 
```javascript
require('dotenv').config()
const fs = require('fs')
const { send } = require('micro')
const microCors = require('micro-cors')
const microJwtAuth = require('micro-jwt-auth')
const match = require('fs-router')(__dirname + '/routes')

const corsMiddleware = microCors({
  allowMethods: [ 'POST', 'GET', 'PUT', 'DELETE' ],
  allowHeaders: [ 'Content-Type', 'Authorization', 'Accept', 'X-Requested-With' ],
  maxAge: 86400,
  origin: '*'
})

const jwtAuthMiddleWare = microJwtAuth(fs.readFileSync(process.env.JWT_PUBLIC_KEY_PATH), ['/signin'])

const applyMiddlewares = (...middlewares) => middlewares.reduce((f, g) => (...args) => f(g(...args)))

const handleRequest = async (req, res) => {
  await sleep(800)
  const matched = match(req)
  if (matched) return await matched(req, res)
  send(res, 404, { error: 'Not found' })
}

module.exports = applyMiddlewares(
  corsMiddleware,
  jwtAuthMiddleWare
)(handleRequest)
```
So in need to bypass authentication middleware if user send a signin request.
With redux / rxjs, you have the same system if you check / observe the name of the current action.

**Comment by kandros** [comment]
Thanks, the packages has been already updated on NPM

**Comment by kandros** [comment]
@mickaelvalmier 
If you happen to have this kind of problem in other micro libraries, consider using this approach to conditionally load a middleware https://github.com/KaleoSoftware/micro-hoofs/blob/master/index.js

**Comment by boedy** [comment]
Currently only exact paths can be whitelisted (e.g "/login"). I'm currently in the situation where I'm using the [micro-router](https://github.com/pedronauck/micro-router) package and have some dynamic paths I would like to whitelist:

`/resource/:resouce_id`

@mickaelvalmier @kandros what would be a goog way to handle this? I could expend the whitelisting capabilities and send a PR.

**Comment by kandros** [comment]
@boedy I’m not sure if this should be handled here or by the user, as you can already wrap your resource routes without passing a whitelist. 

But feel free to propose something.

**Pull request merged**
